# Generated by Django 2.1.3 on 2018-11-25 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('price', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='room_pictures')),
                ('lie', models.CharField(max_length=1)),
                ('category', models.ForeignKey(default='Однокомнатная', on_delete=django.db.models.deletion.DO_NOTHING, related_name='apartment', to='category.Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='apartment', to='category.Tag')),
            ],
        ),
    ]
